propel:
  database:
      connections:
          askeet:
              adapter: mysql
              classname: Propel\Runtime\Connection\DebugPDO
              dsn: "mysql:host=localhost;dbname=askeet"
              user: root
              password:
              attributes:
