propel:
  database:
      connections:
          askeet:
              adapter: mysql
              classname: Propel\Runtime\Connection\DebugPDO
              dsn: "mysql:host=localhost;dbname=askeet"
              user: root
              password:
              attributes:

  runtime:
      log:
          defaultLogger:
              type: stream
              path: "%kernel.logs_dir%/%kernel.environment%.log"
              level: 300
